### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by John123Allison** [nanohard/gotime#5]
Hi, I think a feature myself and other users would like is to be able to export to CSV for further analysis. I'd be happy to implement this if you'd be interested. Thanks!

**Comment by nanohard** [comment]
Sure, if you have the interest I have the time for a simple merge. Not coding recently due to tendinitis. Happy hacking!

**Comment by John123Allison** [comment]
Cool, when I have time next week I'll get to implementing.

**Comment by John123Allison** [comment]
Hey, I finally found some time to work on this. I have a (I think) working export function, but am having trouble figuring out how to bind it to a key combo. Any guidance would be appreciated. Thanks!

**Comment by nanohard** [comment]
Closing due to PR #8
