### ISSUE TITLE
Module path should be "github.com/nanohard/gotime", not "nanohard/gotime"

### ISSUE THREAD

**Issue by KateGo520** [nanohard/gotime#7]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get github.com/nanohard/gotime`:

```
go: downloading github.com/nanohard/gotime v1.0.2
go: github.com/nanohard/gotime upgrade => v1.0.2
go get: github.com/nanohard/gotime@v1.0.2: parsing go.mod:
        module declares its path as: nanohard/gotime
                but was required as: github.com/nanohard/gotime 
```

###  Fix the module path:
1) Rename the module path to "github.com/nanohard/gotime": https://github.com/nanohard/gotime/blob/master/go.mod#L1 
```
module github.com/nanohard/gotime
go 1.12
require (
	…
) 
```
2) Warning the users not to use the module, get "github.com/nanohard/gotime" in GOPATH mode.

**Comment by KateGo520** [comment]
@nanohard  Could you help me review this issue? Thx :p

**Comment by nanohard** [comment]
Whoops. It was my first time using modules. 😜
Thanks!

**Comment by KateGo520** [comment]
@nanohard   Thank you for your contribution. That helps a lot!
